### ISSUE TITLE
When yerna fails to parse a package.json it errors out without logging the offending file

### ISSUE THREAD

**Issue by nomcopter** [nomcopter/yerna#24]
This makes it very difficult to find the issue in large projects.

**Comment by AlexLandau** [comment]
Were you seeing this in a case where multiple yarnhack processes were run in parallel? I've gotten many of these errors in that situation, with project X failing on project Y's package.json non-deterministically. I assume it's failing due to yarnhack for project Y modifying the package.json concurrently. (I should note that I was starting the yarnhack processes via something other than yerna.)

I just added the following logging in getPackages in packages.js to confirm this:

```
      try {
        const packageJson = JSON.parse(fs.readFileSync(filename));
        return { ... };
      } catch (e) {
        console.log("Failed while trying to parse " + filename)
        throw e;
      }
```
